name: Server API Deploy

on:
  push:
    branches: [ feat/server ]
  pull_request:
    branches: [ feat/server ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo feat/server branch
      uses: actions/checkout@v2
      with:
          repository: mohanzeal/product-comparison
          ref: feat/server
          token: ${{ secrets.CP_PROD_DEPLOY }}

    - name: Get yarn cache directory path
      id: yarn-cache-server-folder
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - name: Cache Yarn server node_modules
      uses: actions/cache@v2
      id: yarn-cache-server
      with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-server-folder.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --immutable

    - name: lint all server dependent packages
      run: yarn server:lint

    - name: test all server dependent packages
      run: yarn server:test
    
    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@master
      id: ssm
      with:
        aws-region: 'ap-south-1'
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        instance-ids: 'i-06b826c5b66f5fe8e'

        working-directory: /home/ec2-user/apps/product-comparison
        command: /bin/sh deploy.sh
        comment: Deploy latest code and restart pm2 app
